### ISSUE TITLE
Excellent set of themes but one request

### ISSUE THREAD

**Issue by sahmed007** [KainNhantumbo/maron-themes#3]
Hi Kain, this is a really good set of themes. Very well crafted with attention to color balance. I must request if it's possible for you to allow any theme to have an operator version.

**Comment by KainNhantumbo** [comment]
Hi sahmed007,
Thanks for your review.

I am still working on the operator versioning, so all themes will have an "operator version" soon.

Best wishes!

**Comment by KainNhantumbo** [comment]
Hi, 
How are been doing?

The latest release has all the themes with an operator version and some enhancements!
Check it out!

Thanks.
